//export const BASE_URL = 'http://44.195.125.80:10050';
export const BASE_URL = 'https://app.thealexapp.com';
//export const BASE_URL = 'http://172.16.100.51:10050';
export const api = {
  getCategories: '/api/v1/user/get-all-category',
  setupProfile: '/api/v1/user/signup',
  verifyOtp: '/api/v1/user/verifyOtp',
  login: '/api/v1/user/login',
  forgetPassword: '/api/v1/user/forgot-password',
  socialLogin: '/api/v1/user/social-login',
  getAllPost: '/api/v1/user/get-posts',
  addPost: '/api/v1/user/create-post',
  likeDislikePost: '/api/v1/user/post/like',
  getUserProfile: '/api/v1/user/profile/',
  getUsersPosts: '/api/v1/user/get-posts-of-user/',
  commentList: '/api/v1/user/post/comment/list/',
  postComment: '/api/v1/user/post/comment/',
  deleteComment: '/api/v1/user/post/comment/delete/',
  createPassword: '/api/v1/user/reset-password',
  getAllNotification: '/api/v1/user/get-notifications',
  savePost: '/api/v1/user/save-post/',
  reportPost: '/api/v1/user/report-post',
  reportUser: '/api/v1/user/report-user',
  blockUser: '/api/v1/user/block-unblock',
  deletePost:'/api/v1/user/delete-post/',
  getTrendingCities: '/api/v1/user/get-top-cities-list',
  makeFollowUser: '/api/v1/user/follow',
  getAllUsers: '/api/v1/user/get-users',
  getAllBusinessList: '/api/v1/user/business/all',
  getAllBusinessCategory: '/api/v1/user/get-all-category',
  getSubCategory: '/api/v1/user/get-subcategory-by-category/',
  getBusinessListingById: '/api/v1/user/business-list/',
  exploreCategories: '/api/v1/user/get-explore-categories',
  exploreSubCategory: '/api/v1/user/get-explore-sub-categories/',
  addFavExplore: '/api/v1/user/add-remove-favourite',
  getAllFollowing: '/api/v1/user/get-follwoing-list/',
  getAllFollowers: '/api/v1/user/get-follower-list/',
  otpresend: '/api/v1/user/resend-otp',
  updateProfile: '/api/v1/user/update-profile',
  getFavouriteExplore: '/api/v1/user/get-favourite-list',
  changePassword: '/api/v1/user/change-password',
  deleteAccount: '/api/v1/user/delete-account',
  getBlockList: '/api/v1/user/block-user-list',
  ourMission: '/api/v1/user/get-content-by-key/our_mission',
  ourVision: '/api/v1/user/get-content-by-key/our_vision',
  privacyPolicy: '/api/v1/user/get-content-by-key/privacy_policy',
  switchUser: '/api/v1/user/switch-account',
  getMyBusiness: '/api/v1/user/business/my',
  createEvent: '/api/v1/user/event/create',
  getMyEventList: '/api/v1/user/events',
  deleteEvent: '/api/v1/user/events/delete/',
  createBusiness: '/api/v1/user/business/create',
  deleteBusiness: '/api/v1/user/business/',
  updateBusiness: '/api/v1/user/business/update/',
  questionAnswerHelp: '/api/v1/user/faq/list',
  submitQuery: '/api/v1/user/submit-query',
  getMyProfile: '/api/v1/user/profile-self',
  deleteNotifcation: '/api/v1/user/delete-notification/',
  notificationCount: '/api/v1/user/notifications/count',
  notificationRead: '/api/v1/user/notifications/',
  getSavedPost: '/api/v1/user/get-saved-post',
  claimBusiness: '/api/v1/user/business-clame/',
  unclaimBusiness : '/api/v1/user/business-unclame/',
  childBusiness: '/api/v1/user/get-sub-child-category-by-sub-category/',
  getChildBusinesses: '/api/v1/user/business-list-by-child/',
  getAllPlaces : '/api/v1/user/get_places_by_user/',
  getAllCountry : '/api/v1/user/get_country_by_user/',
  getAllCities : '/api/v1/user/get_cities_by_user/',
  getAllBusinessFollowers : '/api/v1/user/get-business-follower-list/',
  makeFollowBusiness:'/api/v1/user/business-follow',
  getAllBusinessSearch : '/api/v1/user/business-search?searchQ=',
  getPostById : '/api/v1/user/post/',
  getGlobalSearch : '/api/v1/user/global-search?searchQ=',
  getStory : '/api/v1/user/get-stories?',
  addStory : '/api/v1/user/create-story',
  viewStory : '/api/v1/user/view-story/',
  likeStory : '/api/v1/user/like-story/'
};
