const ImageConstants = {
  leftArrow: require('./../assets/images/left_arrow.png'),
  openEye: require('./../assets/images/openEye.png'),
  closeEye: require('./../assets/images/closeEye.png'),
  downArrow: require('./../assets/images/downArrow.png'),
  verLine: require('./../assets/images/verLine.png'),
  celebrate: require('./../assets/images/celebrate.png'),
  check: require('./../assets/images/check.png'),
  loginbg: require('./../assets/images/loginbg.png'),
  facebook: require('./../assets/images/facebook.png'),
  google: require('./../assets/images/google.png'),
  person: require('./../assets/images/person.png'),
  appIcon: require('./../assets/images/appIcon.png'),
  plus: require('./../assets/images/plus.png'),
  camera: require('./../assets/images/camera.png'),
  media: require('./../assets/images/media.png'),
  search: require('./../assets/images/search.png'),
  bell: require('./../assets/images/bell.png'),
  location: require('./../assets/images/location.png'),
  blue_plus: require('./../assets/images/blue_plus.png'),
  comment: require('./../assets/images/comment.png'),
  h_menu: require('./../assets/images/h_menu.png'),
  save: require('./../assets/images/save.png'),
  send: require('./../assets/images/send.png'),
  send_1: require('./../assets/images/send_1.png'),
  // filled_like: require('./../assets/images/filled_like.png'),
  filled_like: require('./../assets/images/filled_like_new.png'),
  // unlike: require('./../assets/images/unlike.png'),
  unlike: require('./../assets/images/unlike_new.png'),
  add_post: require('./../assets/images/add_post.png'),
  bag: require('./../assets/images/bag.png'),
  chat: require('./../assets/images/chat.png'),
  explore: require('./../assets/images/explore.png'),
  home: require('./../assets/images/home.png'),
  profile: require('./../assets/images/profile.png'),
  audio_off: require('./../assets/images/audio_off.png'),
  audio_on: require('./../assets/images/audio_on.png'),
  apps: require('./../assets/images/apps.png'),
  videoplay: require('./../assets/images/videoplay.png'),
  addAccount: require('./../assets/images/add-account.png'),
  map: require('./../assets/images/map.png'),
  block: require('./../assets/images/block.png'),
  help: require('./../assets/images/help.png'),
  info: require('./../assets/images/info.png'),
  policy: require('./../assets/images/policy.png'),
  profileicon: require('./../assets/images/profileicon.png'),
  remove: require('./../assets/images/remove.png'),
  savedpost: require('./../assets/images/savedpost.png'),
  switch: require('./../assets/images/switch.png'),
  security: require('./../assets/images/security.png'),
  rightArrow: require('./../assets/images/rightArrow.png'),
  user: require('./../assets/images/user.png'),
  verticalLine: require('./../assets/images/vertical-line.png'),
  play: require('./../assets/images/play.png'),
  delete: require('./../assets/images/delete.png'),
  delete_new: require('./../assets/images/delete_new.png'),
  edit_comment: require('./../assets/images/edit_comment.png'),
  searchInput: require('./../assets/images/input-search.png'),
  round_insta: require('./../assets/images/round_insta.png'),
  round_fb: require('./../assets/images/round_fb.png'),
  round_linkedin: require('./../assets/images/round_linkedin.png'),
  round_twitter: require('./../assets/images/round_twitter.png'),
  saved: require('./../assets/images/saved.png'),
  globe: require('./../assets/images/globe.png'),
  check_round: require('./../assets/images/check_round.png'),
  blue_location: require('./../assets/images/blue_location.png'),
  bookmark: require('./../assets/images/bookmark.png'),
  phone: require('./../assets/images/phone.png'),
  business_banner: require('./../assets/images/business_banner.png'),
  mail: require('./../assets/images/mail.png'),
  trash: require('./../assets/images/trash.png'),
  calendar: require('./../assets/images/calendar.png'),
  not_found: require('./../assets/images/not_found.png'),
  timer: require('./../assets/images/timer.png'),
  event_banner: require('./../assets/images/event_banner.png'),
  wallet: require('./../assets/images/wallet.png'),
  business_logo: require('./../assets/images/appIcon.png'),
  apple: require('./../assets/images/apple.png'),
  settings : require('./../assets/images/setting.png'),
  edit : require('./../assets/images/write.png'),

  tiktok: require('./../assets/images/tik-tok.png'),
  twitter: require('./../assets/images/twitter.png'),
  like : require('./../assets/images/like.png'),
  instagram : require('./../assets/images/instagram.png'),

  facebook : require('./../assets/images/communication.png'),
  youtube : require('./../assets/images/youtube.png'),
  add_user: require('./../assets/images/add_user.png'),
  share: require('./../assets/images/share.png'),

  maps: require('./../assets/images/maps.png'),
  clock: require('./../assets/images/clock.png'),

  call: require('./../assets/images/call.png'),
  web: require('./../assets/images/web.png'),
};

export default ImageConstants;
